### PR TITLE
Remove railtie, speed up tests, clean up test structure.

### PR DESCRIPTION
**Pull request by chrisrhoden**
Remove railtie which should go in `prx_auth-rails` gem. That gem can include
controller methods, automatic middleware insertion, and a dependency on this
gem.

Clean up test directory structure and guardfile.

Go from from 1.7 assertions/s (post railtie-related test removal) to
104.4 assertions/s.

*note*: went into this gem because I needed to remove the railtie, which makes working in development (where we have a different certificate location and issuer) a pain in the neck.

### CODE REVIEW

**Comment by kookster** [comment]
LGTM, waiting to see if travis passes.

**Comment by chrisrhoden** [comment]
@kookster should be ready for you to look at

**Comment by kookster** [comment]
nice, thanks!

**Comment by chrisrhoden** [comment]
@kookster I didn't mean you should look at it while you're on vacation! Thanks

**Comment by kookster** [comment]
(this was an easy one)

**Pull request merged**
